### ISSUE TITLE
Can't run test if test marked as AutoData and has more then 2 Mock parameters

### ISSUE THREAD

**Issue by Oleksandr-Silin** [AutoFixture/AutoFixture#1082]
AutoFixture version="4.5.1"
xunit version="2.4.1"
.net framework 4.6
moq 4.10.0
VS2017

I updated autofixture from  3.34.2 to 4.5.1 and noticed that NCrunch(3.11.0.9) can't run next code anymore (i've simplified it):
```
using System;
using AutoFixture.Xunit2;
using Moq;
using Xunit;

namespace test2
{
    public class Check
    {
        public class Test
        {
        }

        [Theory, AutoData]
        internal void Some_Test(Mock<Action> act1, Mock<Action> act2, Mock<Test> test)
        {

        }
    }
}
```
Before such code worked. Seems like there some limit on parameters? Couse if i leave 2 then NCrunch(or Unit Test Explorer) can run it. 
```
        [Theory, AutoData]
        internal void Some_Test(Mock<Action> act1, Mock<Test> test)
        {
            var act2 = new Mock<Action>();
        }
```

I also tried to check limits on other types, and seems like it does not allow only to have more then 2 mocks.
How to increase amount of Mock types for "AutoData"?

**Comment by Oleksandr-Silin** [comment]
Update:
it works with AutoFixture 4.4.0. So it has issues with 4.5.0 and 4.5.1

**Comment by Oleksandr-Silin** [comment]
AutoFixture.ObjectCreationExceptionWithPath: AutoFixture was unable to create an instance from Moq.Mock`1[System.Action] because creation unexpectedly failed with exception. Please refer to the inner exception to investigate the root cause of the failure.

Request path:
	Moq.Mock`1[System.Action] act4
	  Moq.Mock`1[System.Action]

Inner exception messages:
	System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
	  System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: value


   at AutoFixture.Kernel.TerminatingWithPathSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\TerminatingWithPathSpecimenBuilder.cs:line 82
   at AutoFixture.BehaviorRoot.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\BehaviorRoot.cs:line 71
   at AutoFixture.Kernel.RecursionGuard.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\RecursionGuard.cs:line 248
   at AutoFixture.Fixture.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Fixture.cs:line 281
   at AutoFixture.Kernel.SpecimenContext.Resolve(Object request) in C:\projects\autofixture\Src\AutoFixture\Kernel\SpecimenContext.cs:line 33
   at AutoFixture.Kernel.SeedIgnoringRelay.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\SeedIgnoringRelay.cs:line 42
   at AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\CompositeSpecimenBuilder.cs:line 52
   at AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\CompositeSpecimenBuilder.cs:line 52
   at AutoFixture.Kernel.Postprocessor`1.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\Postprocessor.cs:line 270
   at AutoFixture.AutoPropertiesTarget.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\AutoPropertiesTarget.cs:line 71
   at AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\CompositeSpecimenBuilder.cs:line 52
   at AutoFixture.Kernel.TerminatingWithPathSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\TerminatingWithPathSpecimenBuilder.cs:line 78
   at AutoFixture.BehaviorRoot.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\BehaviorRoot.cs:line 71
   at AutoFixture.Kernel.RecursionGuard.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\RecursionGuard.cs:line 248
   at AutoFixture.Fixture.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Fixture.cs:line 281
   at AutoFixture.Kernel.SpecimenContext.Resolve(Object request) in C:\projects\autofixture\Src\AutoFixture\Kernel\SpecimenContext.cs:line 33
   at AutoFixture.Kernel.ParameterRequestRelay.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\ParameterRequestRelay.cs:line 32
   at AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\CompositeSpecimenBuilder.cs:line 52
   at AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\CompositeSpecimenBuilder.cs:line 52
   at AutoFixture.Kernel.Postprocessor`1.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\Postprocessor.cs:line 270
   at AutoFixture.AutoPropertiesTarget.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\AutoPropertiesTarget.cs:line 71
   at AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\CompositeSpecimenBuilder.cs:line 52
   at AutoFixture.Kernel.TerminatingWithPathSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\TerminatingWithPathSpecimenBuilder.cs:line 78
   at AutoFixture.BehaviorRoot.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\BehaviorRoot.cs:line 71
   at AutoFixture.Kernel.RecursionGuard.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\RecursionGuard.cs:line 248
   at AutoFixture.Fixture.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Fixture.cs:line 281
   at AutoFixture.Xunit2.AutoDataAttribute.GetData(MethodInfo testMethod) in C:\projects\autofixture\Src\AutoFixture.xUnit2\AutoDataAttribute.cs:line 116
   at Xunit.Sdk.DataDiscoverer.GetData(IAttributeInfo dataAttribute, IMethodInfo testMethod)
   at Xunit.Sdk.XunitTheoryTestCaseRunner.<AfterTestCaseStartingAsync>d__9.MoveNext()
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at AutoFixture.Kernel.AutoPropertiesCommand`1.Execute(Object specimen, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\AutoPropertiesCommand.cs:line 262
   at AutoFixture.Kernel.Postprocessor`1.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\Postprocessor.cs:line 281
   at AutoFixture.AutoPropertiesTarget.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\AutoPropertiesTarget.cs:line 71
   at AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\CompositeSpecimenBuilder.cs:line 52
   at AutoFixture.Kernel.TerminatingWithPathSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\TerminatingWithPathSpecimenBuilder.cs:line 58
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: value
   at Moq.Mock.set_DefaultValue(DefaultValue value) in C:\projects\moq4\src\Moq\Mock.cs:line 138

**Comment by zvirja** [comment]
Hi @Oleksandr-Silin,

First of all take my congratulations with the update! It's a huge step forward and I hope you will enjoy the benefits the newer version of the product brings 😊 

I've took a look at your case and found the culprit. The issue happens when AutoFixture tries to auto-assign properties to a newly created `Mock` object. The auto-generated `DefaultValue` property doesn't suits very well, so `Moq` fails. For the enum values AutoFixture uses the round-robin strategy, which explains why the case with 2 mocks works, while 3 mocks start to crash it. You can easily prove my guess by tweaking the working sample as following:

```c#
[Theory, AutoData]
public void Some_Test_Fewer(DefaultValue dv, Mock<Action> act1, Mock<Test> test)
{
    var act2 = new Mock<Action>();
}
```

It will start to fail, as now the latest `Mock` will receive invalid `DefaultValue` enum value due to round-robin strategy.

As a way to move forward I'd suggest you to install the [`AutoFixture.AutoMoq`](https://www.nuget.org/packages/AutoFixture.AutoMoq/) library. It extends AutoFixture with native Moq support, so it will stop blindly assigning the random enum values to the `Mock` objects. In addition this package additionally provides with other benefits. For instance, each time you deal with interface/abstract class dependencies, AutoFixture will automatically generate mocks for them.

See [this](https://github.com/AutoFixture/AutoFixture/wiki/Cheat-Sheet#auto-mocking-with-moq) tiny doc for documentation. Some links might be found [here](https://stackoverflow.com/questions/4845065/what-is-autofixture-automoq) as well. At this moment our documentation is scattered over the whole web, and in future I hope to have it in one place. But you can easily google for links - samples should be discoverable 😊 

Let me know if you need my further help!

P.S. Sorry for the belated reply - hope to recover next time 😉

**Comment by Oleksandr-Silin** [comment]
TY, for your detailed answer, will try it s soon as will be possible. I'll close it)
