### ISSUE TITLE
AutoMoq can't provide delegates as test parameters

### ISSUE THREAD

**Issue by Kralizek** [AutoFixture/AutoFixture#1094]
I'm working heavily with delegates and I found super conveniente using Moq together with NUnit3 and AutoFixture to set up my tests.

I was quite surprised when I realised that AutoMoq seems not to support the possibility to generate mocks of delegates when requested via parameters.

I had to change so that I manually generate the mock in the body of the test, so nothing serious, yet it would be cool if it could be fixed somehow.

Here is an example from what I'm working on: https://github.com/Kralizek/Nybus/blob/516ff6368058027e27a67724439d791231ddf6f8/tests/Tests.Nybus/NybusConfiguratorExtensionsTests.cs#L57-L67

Here is a gist with a minimal project to reproduce the problem: https://gist.github.com/Kralizek/c9381496056710ef6a95bc99cbafdfdb

Here is the result of running `dotnet test` on the project of the gist

```
Build started, please wait...
Build completed.

Test run for C:\Development\Tests\AutoMoqError\bin\Debug\netcoreapp2.0\AutoMoqError.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.9.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Failed   WontWork
Error Message:
 AutoFixture.ObjectCreationExceptionWithPath : AutoFixture was unable to create an instance from Moq.Mock`1[System.Func`1[System.String]] because creation unexpectedly failed with exception. Please refer to the inner exception to investigate the root cause of the failure.

Request path:
	System.Func`1[System.String] func
	  System.Func`1[System.String]
	    Moq.Mock`1[System.Func`1[System.String]]

Inner exception messages:
	System.NotSupportedException: CallBase cannot be used with Delegate mocks.


  ----> System.NotSupportedException : CallBase cannot be used with Delegate mocks.
Stack Trace:
   at AutoFixture.Kernel.TerminatingWithPathSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\TerminatingWithPathSpecimenBuilder.cs:line 82
   at AutoFixture.Kernel.RecursionGuard.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\RecursionGuard.cs:line 167
   at AutoFixture.AutoMoq.MockRelay.Create(Object request, ISpecimenContext context) in C:\Projects\AutoFixture\Src\AutoMoq\MockRelay.cs:line 71
   at AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\CompositeSpecimenBuilder.cs:line 52
   at AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\CompositeSpecimenBuilder.cs:line 52
   at AutoFixture.Kernel.TerminatingWithPathSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\TerminatingWithPathSpecimenBuilder.cs:line 78
   at AutoFixture.Kernel.RecursionGuard.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\RecursionGuard.cs:line 167
   at AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\CompositeSpecimenBuilder.cs:line 52
   at AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\CompositeSpecimenBuilder.cs:line 52
   at AutoFixture.Kernel.Postprocessor`1.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\Postprocessor.cs:line 271
   at AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\CompositeSpecimenBuilder.cs:line 52
   at AutoFixture.Kernel.TerminatingWithPathSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\TerminatingWithPathSpecimenBuilder.cs:line 78
   at AutoFixture.Kernel.RecursionGuard.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\RecursionGuard.cs:line 167
   at AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\CompositeSpecimenBuilder.cs:line 52
   at AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\CompositeSpecimenBuilder.cs:line 52
   at AutoFixture.Kernel.Postprocessor`1.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\Postprocessor.cs:line 271
   at AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\CompositeSpecimenBuilder.cs:line 52
   at AutoFixture.Kernel.TerminatingWithPathSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\TerminatingWithPathSpecimenBuilder.cs:line 78
   at AutoFixture.Kernel.RecursionGuard.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\RecursionGuard.cs:line 167
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at AutoFixture.NUnit3.FixedNameTestMethodBuilder.GetParametersForMethod(IMethodInfo method, IEnumerable`1 parameterValues, Int32 autoDataStartIndex) in C:\Projects\AutoFixture\Src\AutoFixture.NUnit3\FixedNameTestMethodBuilder.cs:line 37
--NotSupportedException
   at Moq.Mock`1.set_CallBase(Boolean value) in C:\projects\moq4\src\Moq\Mock.Generic.cs:line 174
   at AutoFixture.AutoMoq.MockPostprocessor.MockConfigurator`1.Configure(Mock mock) in C:\Projects\AutoFixture\Src\AutoMoq\MockPostprocessor.cs:line 77
   at AutoFixture.AutoMoq.MockPostprocessor.Create(Object request, ISpecimenContext context) in C:\Projects\AutoFixture\Src\AutoMoq\MockPostprocessor.cs:line 67
   at AutoFixture.Kernel.Postprocessor`1.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\Postprocessor.cs:line 271
   at AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\CompositeSpecimenBuilder.cs:line 52
   at AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\CompositeSpecimenBuilder.cs:line 52
   at AutoFixture.Kernel.TerminatingWithPathSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\TerminatingWithPathSpecimenBuilder.cs:line 58

Total tests: 2. Passed: 1. Failed: 1. Skipped: 0.
Test execution time: 1,1088 Seconds
```

**Comment by Kralizek** [comment]
I think the problem is here: https://github.com/AutoFixture/AutoFixture/blob/1e6e8ab446d5ca2ccaf74c051a4cdba0e29c4a62/Src/AutoMoq/MockPostprocessor.cs#L80-L84

[Moq throws a NotSupportedException](https://github.com/moq/moq4/blob/e5197829d13567c7984362829db625da6662a32d/src/Moq/Mock.Generic.cs#L167-L179) if CallBase is enabled for a Delegate
