### ISSUE TITLE
AutoFixture.NUnit3: InlineAutoData with null as parameter

### ISSUE THREAD

**Issue by mjuen** [AutoFixture/AutoFixture#1126]
Hello,

I have a question regarding the `InlineAutoData` Attribute for the NUnit3 extension. 

The following code fails with an exception when executed:
```c#
[Theory]
[InlineAutoData(1L)]
[InlineAutoData(null)]
public void EntityToDto_ShouldWork(long? id, Insurance entity)
{
	entity.Id = id;

	var dto = Mapper.Map<InsuranceDto>(entity);

	dto.Should().BeEquivalentTo(entity);
}
```

```
System.ArgumentNullException: Value cannot be null.
Parameter name: arguments
   at AutoFixture.NUnit3.InlineAutoDataAttribute..ctor(Func`1 fixtureFactory, Object[] arguments)
   at System.Reflection.CustomAttribute._CreateCaObject(RuntimeModule pModule, RuntimeType type, IRuntimeMethodInfo pCtor, Byte** ppBlob, Byte* pEndBlob, Int32* pcNamedArgs)
   at System.Reflection.CustomAttribute.CreateCaObject(RuntimeModule module, RuntimeType type, IRuntimeMethodInfo ctor, IntPtr& blob, IntPtr blobEnd, Int32& namedArgs)
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1& derivedAttributes)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeMethodInfo method, RuntimeType caType, Boolean inherit)
   at System.Reflection.RuntimeMethodInfo.GetCustomAttributes(Type attributeType, Boolean inherit)
   at NUnit.Framework.Extensions.GetAttributes[T](ICustomAttributeProvider attributeProvider, Boolean inherit)
   at NUnit.Framework.Internal.Builders.DefaultTestCaseBuilder.BuildFrom(IMethodInfo method, Test parentSuite)
   at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.AddTestCasesToFixture(TestFixture fixture, IPreFilter filter)
   at NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.BuildFrom(ITypeInfo typeInfo, IPreFilter filter, ITestFixtureData testFixtureData)
   at NUnit.Framework.TestFixtureAttribute.BuildFrom(ITypeInfo typeInfo, IPreFilter filter)+MoveNext()
   at NUnit.Framework.Internal.Builders.DefaultSuiteBuilder.BuildFrom(ITypeInfo typeInfo, IPreFilter filter)
```

Is this supposed to happen or did I miss something? 

When I change the second `InlineAutoData` to `[InlineAutoData(new object[] { null })]`, everything works fine. 

----------------------------------------------

Target framework: .NET Core 2.2

Package versions:

![image](https://user-images.githubusercontent.com/7404431/59162824-feecd580-8af7-11e9-8dc4-5c4d39bc500c.png)

**Comment by zvirja** [comment]
Hi @mjuen,

Thanks for registering the issue!

While I understand technical reasoning behind it, I think it's a missing feature we need to implement. It will align nicely with the `[TestCase()]` attribute which converts `null` value the `new object[1]` array. xUnit does the same.

I think everybody will win from this behavior as `null` value makes no sense for the attribute.

I'm registering it as a potential feature. You can send a PR if you have time 😉
