### ISSUE TITLE
FakeItEasy 5.4.1, 5.50 internal class change broke AutoFixture.AutoFakeItEasy

### ISSUE THREAD

**Issue by blairconrad** [AutoFixture/AutoFixture#1155]
I was preparing to test AutoFixture.AutoFakeItEasy with an early FakeItEasy 6.0.0 candidate, and found that many of the unit tests broke with output like

```
X AutoFixture.AutoFakeItEasy.UnitTest.FixtureIntegrationTest.WithConfigureMembers_GetOnlyPropertiesReturnValueFromFixture [6ms]
  Error Message:
   System.MissingMethodException : Method SetReturnValue cannot be found on FakeItEasy.Creation.CastleDynamicProxy.CastleInvocationCallAdapter
  Stack Trace:
     at AutoFixture.AutoFakeItEasy.FakeObjectCall.InvokeWrappedMethod(String methodName, Object[] parameters) in D:\Sandbox\AutoFixture\src\AutoFakeItEasy\FakeObjectCall.cs:line 60
   at AutoFixture.AutoFakeItEasy.MethodCallResult.ApplyToCall(FakeObjectCall fakeObjectCall) in D:\Sandbox\AutoFixture\src\AutoFakeItEasy\MethodCallResult.cs:line 18
   at FakeItEasy.Core.FakeManager.ApplyBestRule(IInterceptedFakeObjectCall fakeObjectCall) in C:\projects\fakeiteasy\src\FakeItEasy\Core\FakeManager.cs:line 268
   at FakeItEasy.Core.FakeManager.FakeItEasy.Core.IFakeCallProcessor.Process(InterceptedFakeObjectCall fakeObjectCall) in C:\projects\fakeiteasy\src\FakeItEasy\Core\FakeManager.cs:line 167
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.ObjectProxy_19.get_GetOnlyProperty()
   at AutoFixture.AutoFakeItEasy.UnitTest.FixtureIntegrationTest.WithConfigureMembers_GetOnlyPropertiesReturnValueFromFixture() in D:\Sandbox\AutoFixture\src\AutoFakeItEasyUnitTest\FixtureIntegrationTest.cs:line 266
```

In FakeItEasy, we'd removed the publicly-visible `SetReturnValue` member on the _internal_ class `CastleInvocationCallAdapter` in the 5.4.1 release as part of #1697, leaving only the explicitly-implemented interface member.

I propose, partly based on my own reasoning and on comments @thomaslevesque made in  FakeItEasy/FakeItEasy#1736, that we work around the problem in `FakedObjectCall`. This would mean that recent AutoFixture.AutoFakeItEasys will work with all FakeItEasys <= 5.4.0 and the next AutoFakeItEasy released would work with all FakeItEasys.

Specifically, we should look methods and properties on interfaces implemented by the type of the object passed to `FakedObjectCall` in addition to directly on the type. PR forthcoming.

**Comment by blairconrad** [comment]
Fixed by @aivascu's #1209.
