### ISSUE TITLE
🐛 ReadonlyCollectionPropertiesBehavior causes InvalidCastException when used with OmitOnRecursionBehavior

### ISSUE THREAD

**Issue by ArturDorochowicz** [AutoFixture/AutoFixture#1341]
### Describe the Bug

When `ReadonlyCollectionPropertiesBehavior` and `OmitOnRecursionBehavior` are used together, there may be an `InvalidCastException` thrown from `CreateMany` call in `ReadonlyCollectionPropertiesCommand`
> InvalidCastException
> Unable to cast object of type 'AutoFixture.Kernel.OmitSpecimen' to type 'System.Collections.Generic.IEnumerable`1[System.Object]'.`

https://github.com/AutoFixture/AutoFixture/blob/730b47884975d0c1256209073a719a9fe510d8a9/Src/AutoFixture/Kernel/ReadonlyCollectionPropertiesCommand.cs#L64-L66

### Scenario

```csharp
using System.Collections.Generic;
using System.Linq;
using AutoFixture;
using Xunit;

#nullable enable

public class Bugs
{

public class RecursionModel
{
    public RecursionItem? Item { get; set; }
}

public class RecursionItem
{
    public List<RecursionItem> Items { get; } = new();
}

    [Fact]
    public void OmitRecursion()
    {
        var fixture = new Fixture();
        fixture.Behaviors.Add(new ReadonlyCollectionPropertiesBehavior());
        fixture.Behaviors.OfType<ThrowingRecursionBehavior>().ToList()
            .ForEach(b => fixture.Behaviors.Remove(b));
        fixture.Behaviors.Add(new OmitOnRecursionBehavior());
 
        // Throws
        fixture.Create<RecursionModel>();
    }
}
/*
System.InvalidCastException
Unable to cast object of type 'AutoFixture.Kernel.OmitSpecimen' to type 'System.Collections.Generic.IEnumerable`1[System.Object]'.
   at AutoFixture.SpecimenFactory.CreateMany(ISpecimenContext context, Type type)
   at AutoFixture.Kernel.ReadonlyCollectionPropertiesCommand.Execute(Object specimen, ISpecimenContext context)
   at AutoFixture.Kernel.Postprocessor`1.Create(Object request, ISpecimenContext context)
   at AutoFixture.Fixture.Create(Object request, ISpecimenContext context)
   at AutoFixture.Kernel.SpecimenContext.Resolve(Object request)
   at AutoFixture.Kernel.SeedIgnoringRelay.Create(Object request, ISpecimenContext context)
   at AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
   at AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
   at AutoFixture.Kernel.Postprocessor`1.Create(Object request, ISpecimenContext context)
   at AutoFixture.AutoPropertiesTarget.Create(Object request, ISpecimenContext context)
   at AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
   at AutoFixture.Kernel.TerminatingWithPathSpecimenBuilder.Create(Object request, ISpecimenContext context)
*/
```

### Expected Behavior

The code above should not throw. The first level collection should probably be empty

### More Information

Using AutoFixture 4.17

**Comment by bestsoftever** [comment]
@ArturDorochowicz - is this still an issue? I can't reproduce this.
