### ISSUE TITLE
🐛 v5 `MemberAutoData` does not find static members on base classes

### ISSUE THREAD

**Issue by pinkfloydx33** [AutoFixture/AutoFixture#1464]
### Describe the Bug
`MemberAutoData` does not find static members on base classes and requires that you specify the `Type` constructor parameter. This is different from xUnit behavior where the base class will also be searched. `MemberAutoData` didn't work properly in v4 so I have nothing to compare it to. I assume this is a bug, at least its a tad inconvenient.

### Scenario
```csharp
public class TestBaseClass 
{
     public static IEnumerable<object[]> GetData => Enumerable.Empty<object[]>();
}

public class TestClass : TestBaseClass 
{
     [Fact]
     [MemberAutoData(nameof(GetData)] // does not work
     [MemberAutoData(typeof(TestBaseClass),  nameof(GetData)] // works
     public void MyTest(object input) {  }
}
```
When running the tests, an exception is throw by the test runner:

```
System.ArgumentException
Could not find public static member (property, field, or method) named 'GetData' on TestClass
   at AutoFixture.Xunit2.Internal.MemberTestCaseSource.GetTestCases(MethodInfo method)
   at AutoFixture.Xunit2.Internal.AutoTestCaseSource.CombineValues(MethodInfo methodInfo, ITestCaseSource source)+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Xunit.Sdk.XunitTheoryTestCaseRunner.AfterTestCaseStartingAsync() in /_/src/xunit.execution/Sdk/Frameworks/Runners/XunitTheoryTestCaseRunner.cs:line 147
```

### Expected Behavior
Member data in test base class is found without having to specify the `Type` argument.

Thanks!

**Comment by micheltol** [comment]
I Think this issue can be closed, right? @aivascu @pinkfloydx33

**Comment by aivascu** [comment]
@micheltol yes this was fixed in AutoFixture/AutoFixture#1477. Thanks for pointing it out.

**Comment by pinkfloydx33** [comment]
It seems like the same issue exists for Xunit3. I don't know if this should've covered that or not.

**Comment by aivascu** [comment]
@pinkfloydx33 probably the fix wasn't included in the PR that migrated the code. I'll have a look.

**Comment by pinkfloydx33** [comment]
Actually it's working. I was thrown off by AutoFixture/AutoFixture.xUnit3#1
