### ISSUE TITLE
Using Customize<T>(..) for defaults

### ISSUE THREAD

**Issue by lazytarget** [AutoFixture/AutoFixture#321]
I've been using AutoFixture for sometime now and only recently discovered `Customize<T>(..)`. Which, by my understanding can be used for setting build/generation rules on a higher level. To avoid having to set With and Without on each `Build<T>(..)`.

My question is:
If I customize with: `Fixture.Customize<MyObj>(x => x.Without(y => y.ID))`
and later I wish to set the ID property with a `Build<MyObj>().With(x => x.ID)`, it throws an exception saying "The specimen created for assignment is not compatible with System.Int64". Is this a bug or expected behavior? I can set the property with `Build<MyObj>().With(x => x.ID, fixture.Create<long>())`, but that means more typing ^^

Is there another way of setting default values?
Sorry if I am posting this on the wrong forum.

**Comment by ploeh** [comment]
@LazyTarget, do you consider your question answered?

**Comment by LazyTarget** [comment]
This didn't answer my question, but we can close this as I am working on other projects now

**Comment by ploeh** [comment]
I may have misread the original question, then; I've now edited the question to format code as code, so that the generic type arguments are visible. I'll take a look later today.

**Comment by ploeh** [comment]
Hmm... This actually looks like a bug, although I've still not gotten to the bottom of the issue. However, using the type definitions posted by @moodmosaic above, this test seems to reproduce the issue:

```C#
[Fact]
public void Repro()
{
    var fixture = new Fixture();
    fixture.Behaviors.Add(new TracingBehavior());
    fixture.Customize<Route>(x => x.Without(y => y.Id));
    var r = fixture.Build<Route>().With(x => x.Id).Create(); // throws
    Assert.NotEqual(default(long), r.Id);
}
```

The output of running this test is:

```
Test 'ClassLibrary1.Tests.Repro' failed: System.InvalidOperationException : The specimen created for assignment is not compatible with System.Int64.
	at Ploeh.AutoFixture.Kernel.BindingCommand`2.CreateAnonymousValue(ISpecimenContext container)
	at Ploeh.AutoFixture.Kernel.BindingCommand`2.Execute(Object specimen, ISpecimenContext context)
	at Ploeh.AutoFixture.Kernel.Postprocessor`1.Create(Object request, ISpecimenContext context)
	at Ploeh.AutoFixture.Kernel.Postprocessor`1.Create(Object request, ISpecimenContext context)
	at Ploeh.AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
	at Ploeh.AutoFixture.Kernel.FilteringSpecimenBuilder.Create(Object request, ISpecimenContext context)
	at Ploeh.AutoFixture.Dsl.NodeComposer`1.Create(Object request, ISpecimenContext context)
	at Ploeh.AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
	at Ploeh.AutoFixture.Kernel.RecursionGuard.Create(Object request, ISpecimenContext context)
	at Ploeh.AutoFixture.Kernel.TracingBuilder.Create(Object request, ISpecimenContext context)
	at Ploeh.AutoFixture.Kernel.TraceWriter.Create(Object request, ISpecimenContext context)
	at Ploeh.AutoFixture.Dsl.CompositeNodeComposer`1.Create(Object request, ISpecimenContext context)
	at Ploeh.AutoFixture.Kernel.SpecimenContext.Resolve(Object request)
	at Ploeh.AutoFixture.Kernel.SeedIgnoringRelay.Create(Object request, ISpecimenContext context)
	at Ploeh.AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
	at Ploeh.AutoFixture.Kernel.FilteringSpecimenBuilder.Create(Object request, ISpecimenContext context)
	at Ploeh.AutoFixture.Dsl.NodeComposer`1.Create(Object request, ISpecimenContext context)
	at Ploeh.AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
	at Ploeh.AutoFixture.Kernel.RecursionGuard.Create(Object request, ISpecimenContext context)
	at Ploeh.AutoFixture.Kernel.TracingBuilder.Create(Object request, ISpecimenContext context)
	at Ploeh.AutoFixture.Kernel.TraceWriter.Create(Object request, ISpecimenContext context)
	at Ploeh.AutoFixture.Dsl.CompositeNodeComposer`1.Create(Object request, ISpecimenContext context)
	at Ploeh.AutoFixture.Kernel.SpecimenContext.Resolve(Object request)
	at Ploeh.AutoFixture.SpecimenFactory.Create[T](ISpecimenContext context, T seed)
	at Ploeh.AutoFixture.SpecimenFactory.Create[T](ISpecimenContext context)
	at Ploeh.AutoFixture.SpecimenFactory.Create[T](ISpecimenBuilder builder)
	at Ploeh.AutoFixture.SpecimenFactory.Create[T](IPostprocessComposer`1 composer)
	Code.cs(33,0): at ClassLibrary1.Tests.Repro()

Output from ClassLibrary1.Tests.Repro:
  Requested: Ploeh.AutoFixture.Kernel.SeededRequest
      Requested: ClassLibrary1.Route
        Requested: Int64 Id
        Created: Ploeh.AutoFixture.Kernel.OmitSpecimen
```

As we can see from the trace, the request is correctly for an `Int64` property called `Id`, but the returned value is an `OmitSpecimen`, which very strongly suggests that the customization is still in effect. This hypothesis is confirmed by removing the `Customize<Route>` call:

```C#
[Fact]
public void Works()
{
    var fixture = new Fixture();
    var r = fixture.Build<Route>().With(x => x.Id).Create();
    Assert.NotEqual(default(long), r.Id);
}
```

This test passes.

As the documentation of the `Build` method states

> the Build method chain is best understood as a one-off Customization. It bypasses all Customizations on the Ploeh.AutoFixture.Fixture instance.

Thus, the observed behaviour seems to be incorrect.

**Comment by erlis** [comment]
Hi, 

I'm having a similar question as the OP. I was hoping to use Customize in the way I was using a extension method before. This is the code I used to have: 

```C#
Fixture fixture = new Fixture();
fixture.MyModelBuilder().With(x => x.Attr1, "AnotherValue").....Create();
````
Inside `MyModelBuilder` I'm setting default values for some properties. I was hoping I could use the Customize method and then later if I use `fixture.Build<MyModel>` the same customization applied. But after reading the documentation for the build method I know realize is impossible to use Build for this purpose. 

I'm pretty sure there must be a valid reason for why `Build` cannot use the build used on the customization, but my question is this: Is it possible to access it somehow? 

The other option I have is just to go ahead with the customization and do something like this: 

```C#
Fixture fixture = new Fixture();
fixture.Customize<MyModel>(x => x
    .With(....) )
var myModel = fixture.Create<MyModel>();
myModel.Attr1 = "Another Value";
... // more customizations
```
a bit of boilerplate code on the example, I'm not really using the fixture like this because I have it as a DataAttribute with the customization applied, but the idea is that I can create the Object and change whatever value I need without the builder. 

I don't know if this is the way to go, but if you have any recommendation it will be greatly appreciated.
