### ISSUE TITLE
DataAnnotations RangeAttribute causes arithmetic OverflowException

### ISSUE THREAD

**Issue by kristofferahl** [AutoFixture/AutoFixture#453]
We have a simple model that looks like this:

**Model**

```
public class AddRequest
{
    [Range(1, long.MaxValue, ErrorMessage = "Id is not in range")]
    public long CustomerId { get; set; }

    public int PartnerId { get; set; }

    public string Text { get; set; }
}
```

**Test**

```
var fixture = new Fixture();
var request = fixture.Freeze<AddRequest>();
```

**Exception**

When using autofixures Freeze method to create an instance we get the following exception:

```
  System.OverflowException : Arithmetic operation resulted in an overflow.
     at System.Double.System.IConvertible.ToInt64(IFormatProvider provider)
     at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
     at Ploeh.AutoFixture.DataAnnotations.RangeAttributeRelay.Create(RangeAttribute rangeAttribute, Object request)
     at Ploeh.AutoFixture.DataAnnotations.RangeAttributeRelay.Create(Object request, ISpecimenContext context)
     at Ploeh.AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
     at Ploeh.AutoFixture.CustomizationNode.Create(Object request, ISpecimenContext context)
     at Ploeh.AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
     at Ploeh.AutoFixture.Kernel.TracingBuilder.Create(Object request, ISpecimenContext context)
     at Ploeh.AutoFixture.Kernel.TerminatingWithPathSpecimenBuilder.Create(Object request, ISpecimenContext context)
     at Ploeh.AutoFixture.BehaviorRoot.Create(Object request, ISpecimenContext context)
     at Ploeh.AutoFixture.Kernel.RecursionGuard.Create(Object request, ISpecimenContext context)
     at Ploeh.AutoFixture.Fixture.Create(Object request, ISpecimenContext context)
     at Ploeh.AutoFixture.Kernel.SpecimenContext.Resolve(Object request)
     at Ploeh.AutoFixture.Kernel.AutoPropertiesCommand`1.Execute(Object specimen, ISpecimenContext context)
     at Ploeh.AutoFixture.Kernel.Postprocessor`1.Create(Object request, ISpecimenContext context)
     at Ploeh.AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
     at Ploeh.AutoFixture.Kernel.TracingBuilder.Create(Object request, ISpecimenContext context)
     at Ploeh.AutoFixture.Kernel.TerminatingWithPathSpecimenBuilder.Create(Object request, ISpecimenContext context)
     at Ploeh.AutoFixture.BehaviorRoot.Create(Object request, ISpecimenContext context)
     at Ploeh.AutoFixture.Kernel.RecursionGuard.Create(Object request, ISpecimenContext context)
     at Ploeh.AutoFixture.Fixture.Create(Object request, ISpecimenContext context)
     at Ploeh.AutoFixture.Kernel.SpecimenContext.Resolve(Object request)
     at Ploeh.AutoFixture.Kernel.SeedIgnoringRelay.Create(Object request, ISpecimenContext context)
     at Ploeh.AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
     at Ploeh.AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
```

We managed to figure out that using long.MaxValue - 512 seems to work. Anyone else seen this issue and have a solution that works?

**Comment by ploeh** [comment]
Thank you for reporting this. It looks like a bug, but I have yet to make a full analysis yet.

**Comment by moodmosaic** [comment]
[RangeAttribute](https://msdn.microsoft.com/en-us/library/system.componentmodel.dataannotations.rangeattribute.aspx) has 3 constructor overloads:

* RangeAttribute(Double, Double)
* RangeAttribute(Int32, Int32)
* RangeAttribute(Type, String, String)

The provided repro though uses a `long`:

```
[Range(1, long.MaxValue, ErrorMessage = "Id is not in range")]
public long CustomerId { get; set; }
```

This goes into the 3rd constructor overload, the weakly typed one taking a `Type`.

Here's a wild guess:

Passing a `long` or `Int64` makes the RangeAttribute to convert its internal state into a `Double` :open_mouth:

>System.OverflowException : Arithmetic operation resulted in an overflow.
     at **System.Double**.System.IConvertible.ToInt64(IFormatProvider provider)

---

At least we can try inside AutoFixture to handle this scenario, by making the algorithm that handles this particular attribute [more robust](https://en.wikipedia.org/wiki/Robustness_principle).

**Comment by kristofferahl** [comment]
Just a clarification. The constructor used is the one taking Double and Double as the arguments.

**Comment by moodmosaic** [comment]
This works, though it requires casting, which in this case is quite cumbersome:

```csharp
public class AddRequest
{
    [Range((double)1, double.MaxValue, ErrorMessage = "Id is not in range")]
    public double CustomerId { get; set; }

    public int PartnerId { get; set; }

    public string Text { get; set; }
}

public void FreezeAddRequest()
{
    var fixture = new Fixture();
    var actual = fixture.Freeze<AddRequest>();
    Assert.NotNull(actual); // Passes.
}
```

It *does* fail with `long`/`Int64` though, most likely for [this](https://github.com/AutoFixture/AutoFixture/issues/453#issuecomment-148298622) reason, so it's correctly labeled as bug.

**Comment by moodmosaic** [comment]
I'm not sure there's an easy way to solve this, as RangeAttribute allows doing the wrong thing apparently.

[RangeAttribute](https://msdn.microsoft.com/en-us/library/system.componentmodel.dataannotations.rangeattribute.aspx) has 3 constructor overloads:

* RangeAttribute(Double, Double)
* RangeAttribute(Int32, Int32)
* RangeAttribute(Type, String, String)

However it's possible to do this:

```csharp
[Range(1, long.MaxValue)]
public long SomeProperty { get; set; }
```

This falls in the first overload where:
 * `1` gets casted into a `Double`
 * `long.MaxValue` gets casted into

**Comment by ChrisLangsenkamp** [comment]
This fails to compile with Overflow error:
`Range(-9223372036854775808, 9223372036854775807)`

This compiles, but may fail at runtime?
`Range(Int64.MinValue, Int64.MaxValue)`

**Comment by TheBigSot** [comment]
I did a workaround to ignore the error in RangeAttributeRelay, so I don't have to change the classes.
````

    public class SomethingTests
    {
        [Test]
        public void TestSomething()
        {
            // Arrange 
            var fixture = new Fixture();
            fixture.Customize(new AutoMoqCustomization());
            Fix(fixture);
            
            var code = fixture.Create<SomeClass>();
        }

```
        private void Fix(Fixture fixture)
        {
            var custom = fixture.Customizations.ToList();
            // Decorate the RangeAttributeRelay with an error handler 
            var relay = custom.FirstOrDefault(c => c is RangeAttributeRelay) as RangeAttributeRelay;
            if (relay != null)
            {
                fixture.Customizations.Remove(relay);
                fixture.Customizations.Add(new IgnoreErrorOfRangeAttributeRelay(relay));
            }
        }
    }
    public class IgnoreErrorOfRangeAttributeRelay : ISpecimenBuilder
    {
        private readonly RangeAttributeRelay _requestRelay;

        public IgnoreErrorOfRangeAttributeRelay(RangeAttributeRelay requestRelay)
        {
            _requestRelay = requestRelay;
        }

        public object Create(object request, ISpecimenContext context)
        {
            try
            {
                return _requestRelay.Create(request, context);
            }
            catch (Exception ex)
            {
                return new NoSpecimen();
            }
        }
    }
