### ISSUE TITLE
NUnit+NSubstitute. Auto-data attribute does not support customizations

### ISSUE THREAD

**Issue by OlRomchik** [AutoFixture/AutoFixture#477]
The following test does not work 

    public class Test
    {
        [Theory, AutoMockData]
        public void TestMethod([Frozen]ITest test)
        {
            //// Empty test should be green
        }

        private class AutoMockDataAttribute : AutoDataAttribute
        {
            public AutoMockDataAttribute()
                : base(new Fixture().Customize(new AutoConfiguredNSubstituteCustomization()))
            {
                this.Fixture.Customize<ITest>(build => build.Do(x => x.Test().Returns(420)));
            }
        } 
    }

    public interface ITest
    {
        int Test();
    }

The code throws an exception:

	Ploeh.AutoFixture.ObjectCreationException : The decorated ISpecimenBuilder could not create a specimen based on the request: ConsoleApplication3.Tests.ITest. This can happen if the request represents an interface or abstract class; if this is the case, register an ISpecimenBuilder that can create specimens based on the request. If this happens in a strongly typed Build<T> expression, try supplying a factory using one of the IFactoryComposer<T> methods.
	    at Ploeh.AutoFixture.Kernel.NoSpecimenOutputGuard.Create(Object request, ISpecimenContext context)
	    at Ploeh.AutoFixture.Kernel.Postprocessor`1.Create(Object request, ISpecimenContext context)
	    at Ploeh.AutoFixture.Kernel.Postprocessor`1.Create(Object request, ISpecimenContext context)
	    at Ploeh.AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
	    at Ploeh.AutoFixture.Kernel.FilteringSpecimenBuilder.Create(Object request, ISpecimenContext context)
	    at Ploeh.AutoFixture.Dsl.NodeComposer`1.Create(Object request, ISpecimenContext context)
	    at Ploeh.AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
	    at Ploeh.AutoFixture.CustomizationNode.Create(Object request, ISpecimenContext context)
	    at Ploeh.AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
	    at Ploeh.AutoFixture.Kernel.TracingBuilder.Create(Object request, ISpecimenContext context)
	    at Ploeh.AutoFixture.Kernel.TerminatingWithPathSpecimenBuilder.Create(Object request, ISpecimenContext context)
	    at Ploeh.AutoFixture.BehaviorRoot.Create(Object request, ISpecimenContext context)
	    at Ploeh.AutoFixture.Kernel.RecursionGuard.Create(Object request, ISpecimenContext context)
	    at Ploeh.AutoFixture.Fixture.Create(Object request, ISpecimenContext context)
	    at Ploeh.AutoFixture.FreezeOnMatchCustomization.FreezeTargetType(IFixture fixture)
	    at Ploeh.AutoFixture.FreezeOnMatchCustomization.FreezeTypeForMatchingRequests(IFixture fixture)
	    at Ploeh.AutoFixture.FreezeOnMatchCustomization.Customize(IFixture fixture)
	    at Ploeh.AutoFixture.Fixture.Customize(ICustomization customization)
	    at Ploeh.AutoFixture.NUnit2.AutoDataAttribute.CustomizeFixture(ParameterInfo p)
	    at Ploeh.AutoFixture.NUnit2.AutoDataAttribute.GetData(MethodInfo method)
	    at Ploeh.AutoFixture.NUnit2.Addins.Builders.AutoDataProvider.GetTestCasesFor(MethodInfo method, Test parentSuite)
	    at NUnit.Core.Extensibility.TestCaseProviders.GetTestCasesFor(MethodInfo method, Test suite)

At the same time test is green if I do not use customization in AutoData attribute. 

Should it work?

**Comment by ploeh** [comment]
> Should it work?

Surprisingly: *no*, it shouldn't.

By design, `Customize<T>` overrides all previous customizations for `T`. This was a design decision that I made years ago, because otherwise, there were all sorts of strange corner cases that would make it much more difficult to reason about AutoFixture customizations.

What happens here is that with `Customize<ITest>` you're telling AutoFixture that what comes next is the *exclusive* definition of how `ITest` instances are created. Yet, the expression within the `Do` method relies on something else supplying `x` - an instance of `ITest`. Nothing else can create an instance of `ITest`, because that customization is the exclusive definition of `ITest` generation.

If you really *need* to do something similar to what you've posted, you can configure `ITest` so that it's created by NSubstitute:

```C#
private class AutoMockDataAttribute : AutoDataAttribute
{
    public AutoMockDataAttribute()
        : base(new Fixture().Customize(new AutoConfiguredNSubstituteCustomization()))
    {
        this.Fixture.Register(() =>
            {
                var x = Substitute.For<ITest>();
                x.Test().Returns(420);
                return x;
            });
    }
}
```

Unless you have a particularly special corner case that I can't figure out, however, I think it would be more idiomatic to stick exclusively with the built-in customization, and then configure the test case as needed:

```C#
[Theory, AutoMockData]
public void ConfigurionPerTestCase([Frozen]ITest test)
{
    test.Test().Returns(420);
    Assert.Equal(420, test.Test());
}
```

With that alternative, you don't have to customize `ITest` at all:

```C#
private class AutoMockDataAttribute : AutoDataAttribute
{
    public AutoMockDataAttribute()
        : base(new Fixture().Customize(new AutoConfiguredNSubstituteCustomization()))
    {
    }
}
```

Does this answer your question?

**Comment by OlRomchik** [comment]
I lost that Customize<T> overloads all previous customizations.

Now it is clearer. Thanks a lot.
