### ISSUE TITLE
CreateMany throwing ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by N0ct3** [AutoFixture/AutoFixture#655]
I am using a fixture customized like this:
`fixture.Customize<MyObject>(c => c.FromFactory(new MethodInvoker(new GreedyConstructorQuery())));`
where `MyObject` is a rather simple type inheriting `List`.
When calling 
`fixture.CreateMany<MyObject>();` I sometime get an ArgumentOutOfRangeException.

Here's the full stack trace:
```System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. 
---> System.ArgumentOutOfRangeException: capacity was less than the current size.
Parameter name: value
    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.set_Capacity(Int32 value)
 --- End of inner exception stack trace ---
    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at Ploeh.AutoFixture.Kernel.AutoPropertiesCommand`1.Execute(Object specimen, ISpecimenContext context)
   at Ploeh.AutoFixture.Kernel.Postprocessor`1.Create(Object request, ISpecimenContext context)
   at Ploeh.AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
   at Ploeh.AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
   at Ploeh.AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
   at Ploeh.AutoFixture.Kernel.TracingBuilder.Create(Object request, ISpecimenContext context)
   at Ploeh.AutoFixture.Kernel.TerminatingWithPathSpecimenBuilder.Create(Object request, ISpecimenContext context)
   at Ploeh.AutoFixture.Kernel.RecursionGuard.Create(Object request, ISpecimenContext context)
   at Ploeh.AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
   at Ploeh.AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
   at Ploeh.AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
   at Ploeh.AutoFixture.Kernel.TracingBuilder.Create(Object request, ISpecimenContext context)
   at Ploeh.AutoFixture.Kernel.TerminatingWithPathSpecimenBuilder.Create(Object request, ISpecimenContext context)
   at Ploeh.AutoFixture.Kernel.RecursionGuard.Create(Object request, ISpecimenContext context)
   at Ploeh.AutoFixture.Kernel.StableFiniteSequenceRelay.<>c__DisplayClass0_0.<Create>b__0(Object req)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Ploeh.AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
   at Ploeh.AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
   at Ploeh.AutoFixture.Kernel.TracingBuilder.Create(Object request, ISpecimenContext context)
   at Ploeh.AutoFixture.Kernel.TerminatingWithPathSpecimenBuilder.Create(Object request, ISpecimenContext context)
   at Ploeh.AutoFixture.Kernel.RecursionGuard.Create(Object request, ISpecimenContext context)
   at Ploeh.AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
   at Ploeh.AutoFixture.Kernel.Postprocessor`1.Create(Object request, ISpecimenContext context)
   at Ploeh.AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
   at Ploeh.AutoFixture.Kernel.TracingBuilder.Create(Object request, ISpecimenContext context)
   at Ploeh.AutoFixture.Kernel.TerminatingWithPathSpecimenBuilder.Create(Object request, ISpecimenContext context)
   at Ploeh.AutoFixture.Kernel.RecursionGuard.Create(Object request, ISpecimenContext context)
   at Ploeh.AutoFixture.SpecimenFactory.CreateMany[T](ISpecimenContext context, T seed)
   at Ploeh.AutoFixture.SpecimenFactory.CreateMany[T](ISpecimenContext context)```

The type of the exception, as well as the fact that I cannot reproduce it 100% of the time are confusing me.

**Comment by Zvirja** [comment]
I believe that's because AutoFixture tries to fill properties with public setter for your custom type. It happens that sometimes assigned capacity is less than actual list size - in such cases you get the error.

To overcome that use `.OmitAutoProperties()` to disable auto properties assignment for your custom type:
```csharp
      fixture.Customize<MyObject>(c =>
        c.FromFactory(new MethodInvoker(new GreedyConstructorQuery()))
          .OmitAutoProperties());
```

If you still need AutoProperties - try skipping that particular one:
```csharp
      fixture.Customize<MyObject>(c =>
        c.FromFactory(new MethodInvoker(new GreedyConstructorQuery()))
         .Without(obj => obj.Capacity));
```

That should help.

P.S. Please prettify (wrap lines and and surround with \`\`\`) stacktrace in future - that should help input to not look so scary :)

**Comment by N0ct3** [comment]
Thks for the tip, I will give it a try, and sorry for the formatting, I was not aware of the ```!

**Comment by mikhailshilkov** [comment]
The suggested fix works.

Would it be wise to implement this exclusion on library level? I can't think of a case when setting Capacity of a List<T> would be warranted.

And doing it manually in client code is cumbersome and error-prone.

**Comment by vituha** [comment]
I would recommend to avoid using List<T> in public contracts.
