### ISSUE TITLE
NUnit3: NUnit test failed. Process finished with exit code UnexpectedError (-100)

### ISSUE THREAD

**Issue by sergeyshushlyapin** [AutoFixture/AutoFixture#674]
On `master`, when I call `build.bat`, the build fails with the following error:
```
  1) Fake.UnitTestCommon+FailedTestsException: NUnit test failed. Process finished with exit code UnexpectedError (-100).
   at Fake.Testing.NUnit3.NUnit3(FSharpFunc`2 setParams, IEnumerable`1 assemblies) in C:\code\fake\src\app\FakeLib\UnitTest\NUnit\NUnit3.fs:line 280
   at FSI_0005.Build.clo@36-6.Invoke(Unit _arg7)
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 484
```

AutoFixture CI works [fine](https://ci.appveyor.com/project/AutoFixture/autofixture/build/1.0.299), so I suspect the problem might be in the environment (I use VS2015 Update-2). Any idea what might cause the problem? Thanks!

**Comment by sergeyshushlyapin** [comment]
Uninstalled NUnit. Everything works now :sunglasses:
