### ISSUE TITLE
AutoFixture should fail with meaningful exception when nested properties are being configured

### ISSUE THREAD

**Issue by niksanla2** [AutoFixture/AutoFixture#724]
I have:
```
        public class Response<T> : IResponse<T> where T : IResponseBody
        {
            public T Content { get; set; }
        }

        public class ApplayDeliveryResponseBody : IResponseBody
        {
            public bool? IsAuthenticated { get; set; }
        }
        public interface IResponseBody
        {
            bool? IsAuthenticated { get; set; }
        }

        public interface IResponse<out T> where T : IResponseBody
        {
            T Content { get; }
        }

```
And then I try to call:
```
var _fixture = new Fixture();
_fixture.Build<Response<ApplayDeliveryResponseBody>>()
    .With(x => x.Content.IsAuthenticated, true)
    .Create();
```

I catch an exception:

> "Object does not match target type."

>    at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at Ploeh.AutoFixture.Kernel.BindingCommand`2.TrySetValue(Object specimen, Object value, Type targetType, Action`2 setValue)
   at Ploeh.AutoFixture.Kernel.BindingCommand`2.Execute(Object specimen, ISpecimenContext context)
   at Ploeh.AutoFixture.Kernel.Postprocessor`1.Create(Object request, ISpecimenContext context)
   at Ploeh.AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
   at Ploeh.AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
   at Ploeh.AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
   at Ploeh.AutoFixture.Kernel.RecursionGuard.Create(Object request, ISpecimenContext context)
   at Ploeh.AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
   at Ploeh.AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
   at Ploeh.AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
   at Ploeh.AutoFixture.Kernel.RecursionGuard.Create(Object request, ISpecimenContext context)
   at Ploeh.AutoFixture.SpecimenFactory.Create[T](ISpecimenContext context, T seed)
   at Ploeh.AutoFixture.SpecimenFactory.Create[T](ISpecimenContext context)

**Comment by sergeyshushlyapin** [comment]
Looks like a bug. BTW, it's not about generics. It's about configuring nested properties in general. The sample above can be refined to the following:
```csharp
public class Response
{
    public ApplayDeliveryResponseBody Content { get; set; }
}

public class ApplayDeliveryResponseBody
{
    public bool IsAuthenticated { get; set; }
}

public class Test
{
    [Fact]
    public void CanSetNestedProeprty()
    {
        var fixture = new Fixture();
        fixture.Build<Response>()
            // throws System.Reflection.TargetException : Object does not match target type.
            .With(x => x.Content.IsAuthenticated, true)
            .Create();
    }
}
```

AF tries to set `true` to an instance of the `Response` type rather than `ApplayDeliveryResponseBody`. TBI.

**Comment by zvirja** [comment]
I'd say that existing is not a bug - rather that is a scenario that we don't currently support. Given the nature of how customization currently works (with creation of graph of builders), it might be difficult to support nested properties. The main complication would be to customize the `ApplayDeliveryResponseBody` creation in a way that it's applied when you build `Response`, but is skipped when you build the `ApplayDeliveryResponseBody` object directly.

I'd vote to fix the current behavior by following the [fail-fast](https://en.wikipedia.org/wiki/Fail-fast) approach and throwing a meaningful exception when you try to customize a sub-property. Later we could create a feature to support such scenarios if we believe that it worth it.

@sergeyshushlyapin @moodmosaic @adamchester @ecampidoglio Do you agree with my vision or I'm missing something? If not - I could fire a PR and add an exception throw.

**Comment by moodmosaic** [comment]
I'm a big fan of meaningful, and precise, exception messages, so I agree with what @zvirja proposes:

>throwing a meaningful exception when you try to customize a sub-property via `With()` or `Without()` methods. Later we could create a feature to support such scenarios if we believe that it worth it.

**Comment by zvirja** [comment]
Added a fail-fast guard in v4.
