### ISSUE TITLE
[4.0] Fixture.Create(null,null) throws NullReferenceException

### ISSUE THREAD

**Issue by hubuk** [AutoFixture/AutoFixture#871]
Version: 4.0.0-alpha.253

Following code throws `NullReferenceException`.
```C#
var fixture = new Fixture();
fixture.Create(null, null);
```
with stack trace:
```
at Ploeh.AutoFixture.Kernel.TerminatingWithPathSpecimenBuilder.<>c__DisplayClass11_0.<BuildRequestPathText>b__0(Object r)
at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
at System.Linq.Enumerable.<SelectIterator>d__5`2.MoveNext()
at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)
at Ploeh.AutoFixture.Kernel.TerminatingWithPathSpecimenBuilder.BuildRequestPathText(IEnumerable`1 recordedRequests)
at Ploeh.AutoFixture.Kernel.TerminatingWithPathSpecimenBuilder.Create(Object request, ISpecimenContext context)
at Ploeh.AutoFixture.BehaviorRoot.Create(Object request, ISpecimenContext context)
at Ploeh.AutoFixture.Kernel.RecursionGuard.Create(Object request, ISpecimenContext context)
at Ploeh.AutoFixture.Fixture.Create(Object request, ISpecimenContext context)
```

Version 3 throws `ArgumentNullException` for first parameter `request` with stack trace:
```
at Ploeh.AutoFixture.Kernel.ExactTypeSpecification.IsSatisfiedBy(Object request)
at Ploeh.AutoFixture.Kernel.OrRequestSpecification.IsSatisfiedBy(Object request)
at Ploeh.AutoFixture.Kernel.FilteringSpecimenBuilder.Create(Object request, ISpecimenContext context)
at Ploeh.AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
at Ploeh.AutoFixture.CustomizationNode.Create(Object request, ISpecimenContext context)
at Ploeh.AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context)
at Ploeh.AutoFixture.Kernel.TracingBuilder.Create(Object request, ISpecimenContext context)
at Ploeh.AutoFixture.Kernel.TerminatingWithPathSpecimenBuilder.Create(Object request, ISpecimenContext context)
at Ploeh.AutoFixture.BehaviorRoot.Create(Object request, ISpecimenContext context)
at Ploeh.AutoFixture.Kernel.RecursionGuard.Create(Object request, ISpecimenContext context)
at Ploeh.AutoFixture.Fixture.Create(Object request, ISpecimenContext context)
```

**Comment by zvirja** [comment]
Good catch :+1: Also special thanks for early product testing! :sports_medal:

Actually, that bug was present in the v3 as well, however it was a luck that previously we failed with adequate exception :smile:

I vote to add a guard directly to the `Fixture.Create()` method  to not allow null `request` or `context` values. It doesn't seem that AutoFixture supports `null` requests somehow. 

@moodmosaic @adamchester Do you agree with such a fix or you remember that fixture is supposed to support `null` requests? :confused:

**Comment by moodmosaic** [comment]
Probably that Guard Clause should be added in v4, as I think it'll break tons of existing behavior and tests.

**Comment by zvirja** [comment]
Fixed in v4. Now we fail fast with `ArgumentNullException` if you pass null value to either argument.

@hubuk Thanks again for raising this.
