### ISSUE TITLE
Unable to create Fixture with poco that has Range attribute

### ISSUE THREAD

**Issue by robertbaker** [AutoFixture/AutoFixture#968]
This appears to be a regression bug?
```
AutoFixture.ObjectCreationExceptionWithPath : AutoFixture was unable to create an instance from RangedRequest (MemberType: System.Int32, OperandType: System.Int32 Minimum: [Int32] 1, Maximum: [Int32] 3), most likely because it has no public constructor, is an abstract or non-public type.

   at AutoFixture.Kernel.TerminatingWithPathSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\TerminatingWithPathSpecimenBuilder.cs:line 77
   at AutoFixture.Kernel.RecursionGuard.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\RecursionGuard.cs:line 248
   at AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\CompositeSpecimenBuilder.cs:line 52
   at AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\CompositeSpecimenBuilder.cs:line 52
   at AutoFixture.Kernel.TerminatingWithPathSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\TerminatingWithPathSpecimenBuilder.cs:line 77
   at AutoFixture.Kernel.RecursionGuard.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\RecursionGuard.cs:line 248
   at AutoFixture.Kernel.AutoPropertiesCommand`1.Execute(Object specimen, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\AutoPropertiesCommand.cs:line 260
   at AutoFixture.Kernel.Postprocessor`1.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\Postprocessor.cs:line 285
   at AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\CompositeSpecimenBuilder.cs:line 52
   at AutoFixture.Kernel.TerminatingWithPathSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\TerminatingWithPathSpecimenBuilder.cs:line 77
   at AutoFixture.Kernel.RecursionGuard.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\RecursionGuard.cs:line 248
   at AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\CompositeSpecimenBuilder.cs:line 52
   at AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\CompositeSpecimenBuilder.cs:line 52
   at AutoFixture.Kernel.Postprocessor`1.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\Postprocessor.cs:line 270
   at AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\CompositeSpecimenBuilder.cs:line 52
   at AutoFixture.Kernel.TerminatingWithPathSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\TerminatingWithPathSpecimenBuilder.cs:line 77
   at AutoFixture.Kernel.RecursionGuard.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\RecursionGuard.cs:line 248
   at AutoFixture.SpecimenFactory.Create[T](ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\SpecimenFactory.cs:line 26
```

**Comment by zvirja** [comment]
Hi, thanks for the reporting! Could please share a sample, so I could reproduce it locally? It will simplify the troubleshooting :)

**Comment by robertbaker** [comment]
```
 public class TestClass
    {
        public TestClass()
        {
        }

        [RegularExpression(RegularExpressionConstants.Email)]
        public string Email { get; set; }

        [StringLength(3, MinimumLength =1)]
        public string TestString { get; set; }

        [Range(1,3)]
        public int Testint { get; set; }

        [ListRegularExpression(RegularExpressionConstants.Email)]
        public List<string> TestStrings { get; set; } = new List<string>();
    }
}
```

```public class MoqAutoFixtureSuite
    {
        [Fact]
        public void AutoFixtureWorksWithListRegexValidator()
        {
            //arrange
            var fixture = MoqAutoFixture.GetCustomizedFixture(true,true,true);

            //act
            var entity = fixture.Create<TestClass>();

            //assert
            Assert.NotNull(entity);
            Assert.True(entity.TestStrings.Count > 0);
            foreach (var str in entity.TestStrings)
                Assert.True(Regex.IsMatch(str, RegularExpressionConstants.Email));

            Assert.NotNull(entity.TestString);
            Assert.True(entity.TestString.Length >= 1 && entity.TestString.Length <= 3);

            Assert.True(entity.Testint >= 1 && entity.Testint <= 3);

            Assert.True(Regex.IsMatch(entity.Email, RegularExpressionConstants.Email));
        }
    }```

**Comment by robertbaker** [comment]
I'm looking for a quick workaround or fix to nuget or I'll have to rollback.

**Comment by robertbaker** [comment]
It works in RC1 if that helps, so something recently broke it.

**Comment by robertbaker** [comment]
This is what GetCustomoziedFixture does:

```
  var fixture = new AutoFixture.Fixture()
                .Customize(new AutoFixture.AutoMoq.AutoConfiguredMoqCustomization())            
//add in the ordered customizations (put derived ones before base ones)
            fixture.Customizations.Add(new ListRegularExpressionGenerator());
            fixture.Customizations.Add(new ListRegularExpressionAttributeRelay());
            fixture.Customizations.Add(new RegularExpressionGenerator());
            fixture.Customizations.Add(new RegularExpressionAttributeRelay());
            fixture.Customizations.Add(new RandomRangedNumberGenerator());
            fixture.Customizations.Add(new RangedNumberGenerator());
            fixture.Customizations.Add(new RangeAttributeRelay());
            fixture.Customizations.Add(new ConstrainedStringGenerator());
            fixture.Customizations.Add(new StringLengthAttributeRelay());
```

When I take out ` fixture.Customizations.Add(new RangeAttributeRelay());` it no longer crashes but it fails the test.

**Comment by zvirja** [comment]
It's a bit hard for me to understand what is going on, as a huge number of your own code is involved and you haven't provided me with [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) that is usually attached in such cases 😕  

The reason why it fails might be caused by the reworked approach to handle data annotations. See #920 and #957 for more detail. It might happen that you need to rework the implementation of your custom relays and generators as well.

Also it's a bit confusing to me that you register the following builders again, as all them are already registered by default:
```c#
            fixture.Customizations.Add(new RegularExpressionGenerator());
            fixture.Customizations.Add(new RegularExpressionAttributeRelay());
            fixture.Customizations.Add(new RandomRangedNumberGenerator());
            fixture.Customizations.Add(new RangedNumberGenerator());
            fixture.Customizations.Add(new RangeAttributeRelay());
```

Please review whether you indeed need to do that. If so, it probably makes sense to de-register the default ones using the `NoDataAnnotationsCustomization`.

Also pay attention that the following customizations are mutually exclusive and only one of them should be registered (in v4 the first one is registered, as mentioned in [release notes](https://github.com/AutoFixture/AutoFixture/wiki/v4.0-Release-Notes#%EF%B8%8F-now-randomrangednumbergenerator-is-the-default-handler-of-rangednumberrequest)): 
```c#
            fixture.Customizations.Add(new RandomRangedNumberGenerator());
            fixture.Customizations.Add(new RangedNumberGenerator());
```
I'm not sure I have answers about the reason now as I don't know your code base. Therefore, please try investigating the changes applied in the mentioned PRs to see how your customizations should be adjusted. If you have some specific questions, please ask 😉

**Comment by robertbaker** [comment]
@zvirja I put together a sample project but the tests past. So it is an issue with the custom fixture.

I didn't write this, so bare with me.

We are calling NoDataAnnotationsCustomization. So it appears that the Range is missing a registration

```        public static IFixture GetCustomizedFixture(bool accountKey, bool mongo, bool initializeAutoMapper, params Type[] customizationTypes)
        {
            var fixture = new AutoFixture.Fixture()
                .Customize(new AutoFixture.AutoMoq.AutoConfiguredMoqCustomization())
                .Customize(new ControllerBaseCustomization())
                .Customize(new LoggerFactoryCustomization())
                .Customize(GetOptionalCustomization<AccountKeyValueProviderCustomization>(accountKey))
                .Customize(new ProfileKeyValueProviderCustomization())
                .Customize(GetOptionalCustomization<MongoClientCustomization>(mongo))
                .Customize(new ClaimCustomization())
                .Customize(new IdentityServerClientCustomization())
                .Customize(new ClaimsPrincipalCustomization())
                .Customize(new JsonPatchCustomization())
                .Customize(new NoDataAnnotationsCustomization()) //prevent default handling of data attributes (we add them in ordered next)
                .Customize(new ClientKeyValueProviderCustomization())
                .Customize(new ProgramKeyValueProviderCustomization())
                ;

            //add in the ordered customizations (put derived ones before base ones)
            fixture.Customizations.Add(new ListRegularExpressionGenerator());
            fixture.Customizations.Add(new ListRegularExpressionAttributeRelay());

            fixture.Customizations.Add(new RegularExpressionGenerator());
            fixture.Customizations.Add(new RegularExpressionAttributeRelay());
            fixture.Customizations.Add(new RandomRangedNumberGenerator());
            fixture.Customizations.Add(new RangeAttributeRelay());
            fixture.Customizations.Add(new ConstrainedStringGenerator());
            fixture.Customizations.Add(new StringLengthAttributeRelay());

            foreach (var t in customizationTypes)
                fixture.Customize((ICustomization)Activator.CreateInstance(t));

            fixture.Customize(GetOptionalCustomization<AutoMapperInitializationCustomization>(initializeAutoMapper));

            return fixture;
        }```

**Comment by robertbaker** [comment]
The fix was needing to add fixture.Customizations.Add(new NumericRangedRequestRelay());

**Comment by zvirja** [comment]
Yep, that one is indeed missing from your list.

Notice, the `Customization` property implements the `ICollection<>` interface. Therefore, instead of removing and re-inserting the builders, you can use `fixture.Customization.Insert(0, xxx);` instead - it will push your customizations before the default ones.

I'd strongly recommend to follow the approach above as list of builders registered by default could change (like that already happened) and your customization will become broken or some features will be missing. For instance, you haven't registered the `EnumRangedRequestRelay` responsible for handling the ranged enum members. You might later think that AutoFixture doesn't support this, but it isn't so. Also we might add new supported types in future, however your project will never see them.
