### ISSUE TITLE
Unable to create an instance of IReadOnlyDictionary<T1, T2>

### ISSUE THREAD

**Issue by Kralizek** [AutoFixture/AutoFixture#979]
Hey! I have a class that has a property whose type is `IReadOnlyDictionary<string, SomeType>`. If I try to get this via `AutoDataAttribute` (NUnit3), I get an error (see below)

I thought that v4 had fixed this... Am I wrong?

On a sidenote, is there a way to apply a customization to the instance of Fixture used in the AutoData attribute? (I'm thinking of some default instance available via static accessor)

```
AutoFixture.ObjectCreationExceptionWithPath : AutoFixture was unable to create an instance from System.Collections.Generic.IReadOnlyDictionary`2[System.String,HubSpot.Model.Contacts.VersionedProperty] because it's an interface. There's no single, most appropriate way to create an object implementing the interface, but you can help AutoFixture figure it out.

If you have a concrete class implementing the interface, you can map the interface to that class:

fixture.Customizations.Add(
    new TypeRelay(
        typeof(System.Collections.Generic.IReadOnlyDictionary`2[System.String,HubSpot.Model.Contacts.VersionedProperty]),
        typeof(YourConcreteImplementation)));

Alternatively, you can turn AutoFixture into an Auto-Mocking Container using your favourite dynamic mocking library, such as Moq, FakeItEasy, NSubstitute, and others. As an example, to use Moq, you can customize AutoFixture like this:

fixture.Customize(new AutoMoqCustomization());

See http://blog.ploeh.dk/2010/08/19/AutoFixtureasanauto-mockingcontainer for more details.

Request path:
	HubSpot.Model.Contacts.Contact contact
	  HubSpot.Model.Contacts.Contact
	    System.Collections.Generic.IReadOnlyDictionary`2[System.String,HubSpot.Model.Contacts.VersionedProperty] Properties
	      System.Collections.Generic.IReadOnlyDictionary`2[System.String,HubSpot.Model.Contacts.VersionedProperty]

   at AutoFixture.Kernel.TerminatingWithPathSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\TerminatingWithPathSpecimenBuilder.cs:line 78
   at AutoFixture.BehaviorRoot.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\BehaviorRoot.cs:line 71
   at AutoFixture.Kernel.RecursionGuard.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\RecursionGuard.cs:line 251
   at AutoFixture.Fixture.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Fixture.cs:line 270
   at AutoFixture.Kernel.SpecimenContext.Resolve(Object request) in C:\projects\autofixture\Src\AutoFixture\Kernel\SpecimenContext.cs:line 33
   at AutoFixture.Kernel.SeedIgnoringRelay.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\SeedIgnoringRelay.cs:line 42
   at AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\CompositeSpecimenBuilder.cs:line 52
   at AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\CompositeSpecimenBuilder.cs:line 52
   at AutoFixture.Kernel.Postprocessor`1.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\Postprocessor.cs:line 270
   at AutoFixture.AutoPropertiesTarget.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\AutoPropertiesTarget.cs:line 71
   at AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\CompositeSpecimenBuilder.cs:line 52
   at AutoFixture.Kernel.TerminatingWithPathSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\TerminatingWithPathSpecimenBuilder.cs:line 78
   at AutoFixture.BehaviorRoot.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\BehaviorRoot.cs:line 71
   at AutoFixture.Kernel.RecursionGuard.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\RecursionGuard.cs:line 251
   at AutoFixture.Fixture.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Fixture.cs:line 270
   at AutoFixture.Kernel.SpecimenContext.Resolve(Object request) in C:\projects\autofixture\Src\AutoFixture\Kernel\SpecimenContext.cs:line 33
   at AutoFixture.Kernel.PropertyRequestRelay.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\PropertyRequestRelay.cs:line 32
   at AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\CompositeSpecimenBuilder.cs:line 52
   at AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\CompositeSpecimenBuilder.cs:line 52
   at AutoFixture.Kernel.Postprocessor`1.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\Postprocessor.cs:line 270
   at AutoFixture.AutoPropertiesTarget.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\AutoPropertiesTarget.cs:line 71
   at AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\CompositeSpecimenBuilder.cs:line 52
   at AutoFixture.Kernel.TerminatingWithPathSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\TerminatingWithPathSpecimenBuilder.cs:line 78
   at AutoFixture.BehaviorRoot.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\BehaviorRoot.cs:line 71
   at AutoFixture.Kernel.RecursionGuard.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\RecursionGuard.cs:line 251
   at AutoFixture.Fixture.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Fixture.cs:line 270
   at AutoFixture.Kernel.SpecimenContext.Resolve(Object request) in C:\projects\autofixture\Src\AutoFixture\Kernel\SpecimenContext.cs:line 33
   at AutoFixture.Kernel.AutoPropertiesCommand`1.Execute(Object specimen, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\AutoPropertiesCommand.cs:line 260
   at AutoFixture.Kernel.Postprocessor`1.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\Postprocessor.cs:line 285
   at AutoFixture.AutoPropertiesTarget.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\AutoPropertiesTarget.cs:line 71
   at AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\CompositeSpecimenBuilder.cs:line 52
   at AutoFixture.Kernel.TerminatingWithPathSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\TerminatingWithPathSpecimenBuilder.cs:line 78
   at AutoFixture.BehaviorRoot.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\BehaviorRoot.cs:line 71
   at AutoFixture.Kernel.RecursionGuard.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\RecursionGuard.cs:line 251
   at AutoFixture.Fixture.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Fixture.cs:line 270
   at AutoFixture.Kernel.SpecimenContext.Resolve(Object request) in C:\projects\autofixture\Src\AutoFixture\Kernel\SpecimenContext.cs:line 33
   at AutoFixture.Kernel.SeedIgnoringRelay.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\SeedIgnoringRelay.cs:line 42
   at AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\CompositeSpecimenBuilder.cs:line 52
   at AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\CompositeSpecimenBuilder.cs:line 52
   at AutoFixture.Kernel.Postprocessor`1.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\Postprocessor.cs:line 270
   at AutoFixture.AutoPropertiesTarget.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\AutoPropertiesTarget.cs:line 71
   at AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\CompositeSpecimenBuilder.cs:line 52
   at AutoFixture.Kernel.TerminatingWithPathSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\TerminatingWithPathSpecimenBuilder.cs:line 78
   at AutoFixture.BehaviorRoot.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\BehaviorRoot.cs:line 71
   at AutoFixture.Kernel.RecursionGuard.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\RecursionGuard.cs:line 251
   at AutoFixture.Fixture.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Fixture.cs:line 270
   at AutoFixture.Kernel.SpecimenContext.Resolve(Object request) in C:\projects\autofixture\Src\AutoFixture\Kernel\SpecimenContext.cs:line 33
   at AutoFixture.Kernel.ParameterRequestRelay.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\ParameterRequestRelay.cs:line 32
   at AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\CompositeSpecimenBuilder.cs:line 52
   at AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\CompositeSpecimenBuilder.cs:line 52
   at AutoFixture.Kernel.Postprocessor`1.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\Postprocessor.cs:line 270
   at AutoFixture.AutoPropertiesTarget.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\AutoPropertiesTarget.cs:line 71
   at AutoFixture.Kernel.CompositeSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\CompositeSpecimenBuilder.cs:line 52
   at AutoFixture.Kernel.TerminatingWithPathSpecimenBuilder.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\TerminatingWithPathSpecimenBuilder.cs:line 78
   at AutoFixture.BehaviorRoot.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\BehaviorRoot.cs:line 71
   at AutoFixture.Kernel.RecursionGuard.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Kernel\RecursionGuard.cs:line 251
   at AutoFixture.Fixture.Create(Object request, ISpecimenContext context) in C:\projects\autofixture\Src\AutoFixture\Fixture.cs:line 270
   at AutoFixture.Kernel.SpecimenContext.Resolve(Object request) in C:\projects\autofixture\Src\AutoFixture\Kernel\SpecimenContext.cs:line 33
   at AutoFixture.NUnit3.AutoDataAttribute.Resolve(IParameterInfo parameterInfo) in C:\projects\autofixture\Src\AutoFixture.NUnit3\AutoDataAttribute.cs:line 93
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at AutoFixture.NUnit3.FixedNameTestMethodBuilder.GetParametersForMethod(IMethodInfo method, IEnumerable`1 parameterValues, Int32 autoDataStartIndex) in C:\projects\autofixture\Src\AutoFixture.NUnit3\FixedNameTestMethodBuilder.cs:line 37
```

**Comment by zvirja** [comment]
@Kralizek Nope, the `IReadOnlyDictionary<TKey, TValue>` is not currently supported (see list of supported interfaces [here](https://github.com/AutoFixture/AutoFixture/blob/45832a734087556fa9934a62babd75918b468a6a/Src/AutoFixture/Fixture.cs#L139-L156)). Feel free to fire a PR and add this support if you need it.

**Comment by Kralizek** [comment]
I'll take it since I worked on #941 before ;)

**Comment by Kralizek** [comment]
@zvirja do you have any suggestion about

> On a sidenote, is there a way to apply a customization to the instance of Fixture used in the AutoData attribute? (I'm thinking of some default instance available via static accessor)

**Comment by zvirja** [comment]
> On a sidenote, is there a way to apply a customization to the instance of Fixture used in the AutoData attribute? (I'm thinking of some default instance available via static accessor)

No, AutoFixture doesn't expose such API and expects that you will use your custom `AutoData` attribute with customized fixture instead.

**Comment by Kralizek** [comment]
Uhm. Creating a new AutoData attribute per test fixture feels uselessly repetitive :(

**Comment by zvirja** [comment]
I'm not sure I got your point.

Usually, it's expected that you have a single `CustomAutoData` attribute per test solution, where you apply all the required the global customizations. Therefore, you are not required to create an `AutoData` attribute per test.
