### ISSUE TITLE
GuardClauseAssertion fails on generic parameter with IEquatable<T> constraint

### ISSUE THREAD

**Issue by bordecal** [AutoFixture/AutoFixture#987]
A System.BadImageFormatException is generated when attempting to run GuardClauseAssertion  against a method with a generic parameter with an IEquatable<T> constraint.  e.g.:
```
public void DoSomething<T>(T value) where T : IEquatable<T>
{
    // ...
}
```
This appears to occur during generation of the dynamic dummy for the generic, as indicated by the exception stack trace:
```
Result StackTrace:	
at System.Reflection.Emit.TypeBuilder.TermCreateClass(RuntimeModule module, Int32 tk, ObjectHandleOnStack type)
   at System.Reflection.Emit.TypeBuilder.CreateTypeNoLock()
   at System.Reflection.Emit.TypeBuilder.CreateTypeInfo()
   at AutoFixture.Idioms.GuardClauseAssertion.DynamicDummyType.get_Value() in C:\projects\autofixture\Src\Idioms\GuardClauseAssertion.cs:line 696
   at AutoFixture.Idioms.GuardClauseAssertion.AutoGenericArgument.get_Value() in C:\projects\autofixture\Src\Idioms\GuardClauseAssertion.cs:line 613
   at AutoFixture.Idioms.GuardClauseAssertion.AutoGenericMethod.<GetTypedArguments>b__5_0(Type t) in C:\projects\autofixture\Src\Idioms\GuardClauseAssertion.cs:line 570
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at AutoFixture.Idioms.GuardClauseAssertion.AutoGenericMethod.GetTypedArguments() in C:\projects\autofixture\Src\Idioms\GuardClauseAssertion.cs:line 568
   at AutoFixture.Idioms.GuardClauseAssertion.ResolveUnclosedGenericMethod(MethodInfo methodInfo) in C:\projects\autofixture\Src\Idioms\GuardClauseAssertion.cs:line 361
   at AutoFixture.Idioms.GuardClauseAssertion.Verify(MethodInfo methodInfo) in C:\projects\autofixture\Src\Idioms\GuardClauseAssertion.cs:line 143
   at AutoFixture.Idioms.IdiomaticAssertion.Verify(MethodInfo[] methodInfos) in C:\projects\autofixture\Src\Idioms\IdiomaticAssertion.cs:line 231
   at AutoFixture.Idioms.IdiomaticAssertion.Verify(IEnumerable`1 methodInfos) in C:\projects\autofixture\Src\Idioms\IdiomaticAssertion.cs:line 242
   at AutoFixture.Idioms.IdiomaticAssertion.Verify(Type type) in C:\projects\autofixture\Src\Idioms\IdiomaticAssertion.cs:line 93
   at ...
```
At the moment, I am particularly interested in the case where there is also a `struct` constraint, but the presence of either a `struct` or a `class` constraint has no effect on generation of the exception.

**Comment by zvirja** [comment]
@bordecal Thanks for firing the issue. May I ask you to attach a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of the full scenario, so I can better see it from end to end?

Also please clarify which exact AutoFixture packages you have installed in your project (as we have different glue libraries participating in interface activation).

Thanks.

**Comment by zvirja** [comment]
Ok, I've managed to figure out the scenario:
```c#
[Fact]
public void TestGenericMethod()
{
    var fixture = new Fixture();
    var methodToTest = this.GetType().GetMethod(nameof(DoSomething));

    new GuardClauseAssertion(fixture).Verify(methodToTest);
}

public void DoSomething<T>(T value) where T : IEquatable<T>
{
}
```

If I remove the generic type constrain, it will work as expected.
Let me investigate that in more detail.

**Comment by bordecal** [comment]
Yup, that's pretty much it.   Nothing fancy, and using the latest releases for both AutoFixture and AutoFixture.Idioms.

**Comment by zvirja** [comment]
@bordecal I can confirm it's a bug. I'll try to look into that if I have free time. If you wish, you could also take a look 😉

**Comment by bordecal** [comment]
I'd be happy to take a look, but it'll probably need to wait a few weeks since I'm rather busy with the start of a new project at the moment...

**Comment by Excelzn** [comment]
I took a look at this and although I am pretty sure I figured out what the issue is, actually fixing it is beyond me. The problem only occurs if the method signature is like this:

`public void DoSomething<T>(T value) where T : IEquatable<T>`

and goes away by changing it to this:
`public void DoSomething<T>(T value) where T : IEquatable<AClass>`

The error is thrown by this line in `DynamicDummyType.Value`:
`var dummyType = this.typeBuilder.CreateTypeInfo();`
which is a standard framework call.

This happens with any generic type in the constraints for T.  For example:
`public void DoSomething<T>(T value) where T : ICustomInterface<T>`


Sorry I can't be of more help. Hopefully this info will help someone fix this.

**Comment by zvirja** [comment]
@Excelzn Thanks for the report. I've also tried to quickly solve the issue, however found that a closer look is required. It appeared that `Reflection.Emit` API in .NET is overcomplicated when you operate with `TypeBuilder` like with `Type`.
